### ISSUE TITLE
semantic markup

### ISSUE THREAD

**Issue by ghost** [Jessica044/colmar#2]
https://github.com/Jessica044/colmar/blob/master/index.html#L14-L32

Nice job using HTML5 tags like `header`, `nav`, and `footer` to make your markup more semantic 👍 

Consider adding some more semantic tags like: `main`, `section`, `article`, `aside`, `figure`, etc. This is much better than relying constantly on `div` tags, and can make your code much easier to read and reason about.

**Comment by Jessica044** [comment]
ok thanks!
