### ISSUE TITLE
img alt

### ISSUE THREAD

**Issue by ghost** [Jessica044/colmar#4]
https://github.com/Jessica044/colmar/blob/master/index.html#L27-L29

Give your `img` tags an `alt` attribute with a value that actually describes the image, just in case your website is not able to load it.

Doing so will help improve the accessibility of your website, which might be accessed by visually impaired users on e-readers or other devices that might deliberately neglect images-- as well as any other time that your website is just unable to render images.

**Comment by Jessica044** [comment]
I thought I did on all of them but looks like I did miss the 3 for icon links!
